server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # Ruta hacia ms-a
            - id: ms-a
              uri: lb://ms-a
              predicates:
                - Path=/api/entityA/**
              filters:
                - StripPrefix=0

            # Ruta hacia ms-b
            - id: ms-b
              uri: lb://ms-b
              predicates:
                - Path=/api/entityB/**
              filters:
                - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
