server: 
    port: 8087

spring:
    application:
        name: api-gateway
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:9000
    cloud:
        gateway:
            server: 
                webmvc:
                    routes: 
                        - id: ms1
                          uri: lb://ms1
                          predicates:
                          - Path=/api/entityA/**
                          filters:
                          - StripPrefix=0
                        - id: msb
                          uri: lb://msb
                          predicates:
                          - Path=/api/entityB/**
                          filters:
                          - StripPrefix=0

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
